[use]
plugin = basics

[XMLParse]
separator = /ead/archdesc

[exchange]
value = self().thru(fonds => \
    [ \
        _.set( \
            _.set(_.omit(fonds, ['dsc']), 'baliseEad', 'archdesc'), \
            'niveau', 0 \
        ) \
    ] \
    .concat( \
        [].concat(_.get(fonds, 'dsc.c01')).filter(Boolean) \
        .flatMap(c01 => \
            [ \
                _.set( \
                    _.set( \
                        _.set( \
                            _.set(_.omit(c01, ['c02']), 'baliseEad', 'c01'), \
                            'niveau', 1 \
                        ), \
                        'parentIdentifiant', _.get(fonds, 'did.unitid.$t') \
                    ), \
                    'parentTitre', _.get(fonds, 'did.unittitle.$t') \
                ) \
            ] \
            .concat( \
                [].concat(_.get(c01, 'c02')).filter(Boolean) \
                .flatMap(c02 => \
                    [ \
                        _.set( \
                            _.set( \
                                _.set( \
                                    _.set(_.omit(c02, ['c03']), 'baliseEad', 'c02'), \
                                    'niveau', 2 \
                                ), \
                                'parentIdentifiant', _.get(c01, 'did.unitid.$t') \
                            ), \
                            'parentTitre', _.get(c01, 'did.unittitle.$t') \
                        ) \
                    ] \
                    .concat( \
                        [].concat(_.get(c02, 'c03')).filter(Boolean) \
                        .map(c03 => \
                            _.set( \
                                _.set( \
                                    _.set( \
                                        _.set(c03, 'baliseEad', 'c03'), \
                                        'niveau', 3 \
                                    ), \
                                    'parentIdentifiant', _.get(c02, 'did.unitid.$t') \
                                ), \
                                'parentTitre', _.get(c02, 'did.unittitle.$t') \
                            ) \
                        ) \
                    ) \
                ) \
            ) \
        ) \
    ) \
)

[ungroup]

[swing]
test = pick(['URI', 'uri']).pickBy(_.identity).isEmpty()
[swing/identify]

# Ignore objects with duplicate URI
[dedupe]
ignore = true

# Prevent keys from containing dot path notation (which is forbidden by nodejs mongoDB driver)
[OBJFlatten]
separator = fix('.')
reverse = true
safe = false

# Flated object structure for direct use in Lodex datagrid
[OBJFlatten]
separator = fix('/')
safe = false

# Prevents keys from containing the $ character (which is forbidden by nodejs mongoDB driver)
[exchange]
value = self().mapKeys((value, key) => key.replace(/\$/g, '_'))

# Ensures that each object contains the same keys
[OBJStandardize]

# Uncomment to see each data sent to the database
#[debug]

# Add contextual metadata related to the import
[assign]
path = lodexStamp.importedDate
value = fix(new Date()).thru(d => d.toDateString())
path = lodexStamp.usedParser
value = env('parser')
path = lodexStamp.uploadedFilename
value = env('source')
path = importDateTime
value = fix(new Date()).thru(d => \
  new Intl.DateTimeFormat("fr-FR", { \
    timeZone: "Europe/Paris", \
    year: "numeric", \
    month: "long", \
    day: "numeric", \
    hour: "2-digit", \
    minute: "2-digit", \
    second: "2-digit" \
  }).format(d) \
)
path = uri
value = get('uri').trim()